package com.starfish_studios.another_furniture.registry;

import com.starfish_studios.another_furniture.block.entity.*;
import net.minecraft.world.level.block.entity.BlockEntityType;

import java.util.function.Supplier;

public class AFBlockEntityTypes {
    public static final Supplier<BlockEntityType<ShelfBlockEntity>> SHELF = AFRegistry.registerBlockEntityType("shelf",
            () -> AFRegistry.createBlockEntityType(ShelfBlockEntity::new,
                    AFBlocks.OAK_SHELF.get(),
                    AFBlocks.SPRUCE_SHELF.get(),
                    AFBlocks.BIRCH_SHELF.get(),
                    AFBlocks.JUNGLE_SHELF.get(),
                    AFBlocks.ACACIA_SHELF.get(),
                    AFBlocks.DARK_OAK_SHELF.get(),
                    AFBlocks.MANGROVE_SHELF.get(),
                    AFBlocks.CRIMSON_SHELF.get(),
                    AFBlocks.WARPED_SHELF.get()
            ));

    public static final Supplier<BlockEntityType<ServiceBellBlockEntity>> SERVICE_BELL = AFRegistry.registerBlockEntityType("service_bell",
            () -> AFRegistry.createBlockEntityType(ServiceBellBlockEntity::new, AFBlocks.SERVICE_BELL.get()));

    public static final Supplier<BlockEntityType<PlanterBoxBlockEntity>> PLANTER_BOX = AFRegistry.registerBlockEntityType("planter_box",
            () -> AFRegistry.createBlockEntityType(PlanterBoxBlockEntity::new,
                    AFBlocks.OAK_PLANTER_BOX.get(),
                    AFBlocks.SPRUCE_PLANTER_BOX.get(),
                    AFBlocks.BIRCH_PLANTER_BOX.get(),
                    AFBlocks.JUNGLE_PLANTER_BOX.get(),
                    AFBlocks.ACACIA_PLANTER_BOX.get(),
                    AFBlocks.DARK_OAK_PLANTER_BOX.get(),
                    AFBlocks.MANGROVE_PLANTER_BOX.get(),
                    AFBlocks.CRIMSON_PLANTER_BOX.get(),
                    AFBlocks.WARPED_PLANTER_BOX.get(),
                    AFBlocks.ECOLOGICS_FLOWERING_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.ECOLOGICS_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.ECOLOGICS_COCONUT_PLANTER_BOX.get(),
                    AFBlocks.ECOLOGICS_WALNUT_PLANTER_BOX.get(),
                    AFBlocks.BETTERNETHER_NETHER_REED_PLANTER_BOX.get(),
                    AFBlocks.BETTERNETHER_STALAGNATE_PLANTER_BOX.get(),
                    AFBlocks.BETTERNETHER_WILLOW_PLANTER_BOX.get(),
                    AFBlocks.BETTERNETHER_WART_PLANTER_BOX.get(),
                    AFBlocks.BETTERNETHER_RUBEUS_PLANTER_BOX.get(),
                    AFBlocks.BETTERNETHER_MUSHROOM_FIR_PLANTER_BOX.get(),
                    AFBlocks.BETTERNETHER_NETHER_MUSHROOM_PLANTER_BOX.get(),
                    AFBlocks.BETTERNETHER_ANCHOR_TREE_PLANTER_BOX.get(),
                    AFBlocks.BETTERNETHER_NETHER_SAKURA_PLANTER_BOX.get(),
                    AFBlocks.ARCHITECTS_PALETTE_TWISTED_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_MOSSY_GLOWSHROOM_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_PYTHADENDRON_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_END_LOTUS_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_LACUGROVE_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_DRAGON_TREE_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_TENANEA_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_HELIX_TREE_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_UMBRELLA_TREE_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_JELLYSHROOM_PLANTER_BOX.get(),
                    AFBlocks.BETTEREND_LUCERNIA_PLANTER_BOX.get(),
                    AFBlocks.BLOCKUS_WHITE_OAK_PLANTER_BOX.get(),
                    AFBlocks.BLOCKUS_LEGACY_PLANTER_BOX.get(),
                    AFBlocks.BYG_ASPEN_PLANTER_BOX.get(),
                    AFBlocks.BYG_BAOBAB_PLANTER_BOX.get(),
                    AFBlocks.BYG_BLUE_ENCHANTED_PLANTER_BOX.get(),
                    AFBlocks.BYG_BULBIS_PLANTER_BOX.get(),
                    AFBlocks.BYG_CHERRY_PLANTER_BOX.get(),
                    AFBlocks.BYG_CIKA_PLANTER_BOX.get(),
                    AFBlocks.BYG_CYPRESS_PLANTER_BOX.get(),
                    AFBlocks.BYG_EBONY_PLANTER_BOX.get(),
                    AFBlocks.BYG_ETHER_PLANTER_BOX.get(),
                    AFBlocks.BYG_FIR_PLANTER_BOX.get(),
                    AFBlocks.BYG_GREEN_ENCHANTED_PLANTER_BOX.get(),
                    AFBlocks.BYG_HOLLY_PLANTER_BOX.get(),
                    AFBlocks.BYG_IMPARIUS_PLANTER_BOX.get(),
                    AFBlocks.BYG_LAMENT_PLANTER_BOX.get(),
                    AFBlocks.BYG_JACARANDA_PLANTER_BOX.get(),
                    AFBlocks.BYG_MAHOGANY_PLANTER_BOX.get(),
                    AFBlocks.BYG_WHITE_MANGROVE_PLANTER_BOX.get(),
                    AFBlocks.BYG_MAPLE_PLANTER_BOX.get(),
                    AFBlocks.BYG_NIGHTSHADE_PLANTER_BOX.get(),
                    AFBlocks.BYG_PALM_PLANTER_BOX.get(),
                    AFBlocks.BYG_PINE_PLANTER_BOX.get(),
                    AFBlocks.BYG_RAINBOW_EUCALYPTUS_PLANTER_BOX.get(),
                    AFBlocks.BYG_REDWOOD_PLANTER_BOX.get(),
                    AFBlocks.BYG_SKYRIS_PLANTER_BOX.get(),
                    AFBlocks.BYG_WILLOW_PLANTER_BOX.get(),
                    AFBlocks.BYG_WITCH_HAZEL_PLANTER_BOX.get(),
                    AFBlocks.BYG_ZELKOVA_PLANTER_BOX.get(),
                    AFBlocks.BYG_SYTHIAN_PLANTER_BOX.get(),
                    AFBlocks.CHARM_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.CHARM_EBONY_PLANTER_BOX.get(),
                    AFBlocks.COLORFULAZALEAS_TECAL_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.COLORFULAZALEAS_FISS_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.COLORFULAZALEAS_ROZE_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.COLORFULAZALEAS_AZULE_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.COLORFULAZALEAS_BRIGHT_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.COLORFULAZALEAS_WALNUT_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.COLORFULAZALEAS_TITANIUM_AZALEA_PLANTER_BOX.get(),
                    AFBlocks.VINERY_CHERRY_PLANTER_BOX.get(),
                    AFBlocks.ENDERSCAPE_CELESTIAL_PLANTER_BOX.get(),
                    AFBlocks.PROMENADE_DARK_AMARANTH_PLANTER_BOX.get(),
                    AFBlocks.PROMENADE_CHERRY_OAK_PLANTER_BOX.get(),
                    AFBlocks.PROMENADE_PALM_PLANTER_BOX.get()
            ));

    public static final Supplier<BlockEntityType<DrawerBlockEntity>> DRAWER = AFRegistry.registerBlockEntityType("drawer",
            () -> AFRegistry.createBlockEntityType(DrawerBlockEntity::new,
                    AFBlocks.OAK_DRAWER.get(),
                    AFBlocks.SPRUCE_DRAWER.get(),
                    AFBlocks.BIRCH_DRAWER.get(),
                    AFBlocks.JUNGLE_DRAWER.get(),
                    AFBlocks.ACACIA_DRAWER.get(),
                    AFBlocks.DARK_OAK_DRAWER.get(),
                    AFBlocks.MANGROVE_DRAWER.get(),
                    AFBlocks.CRIMSON_DRAWER.get(),
                    AFBlocks.WARPED_DRAWER.get()
            ));

    public static void init() {}
}
